name: Android Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main # Consider building release here instead of debug

jobs:
  build:
    runs-on: macOS-latest # or ubuntu-latest, which is generally cheaper/faster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: "17"
          # Cache the Gradle dependencies based on the lock file
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # --- Added: Gradle Cache ---
      # This step caches Gradle dependencies and speeds up subsequent runs
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # --- Added: Run Unit Tests ---
      - name: Run Unit Tests
        run: ./gradlew test

      # --- Added: Run Lint ---
      - name: Run Lint
        run: ./gradlew lint # Consider adding --fail-on-empty-delta=false if you only want to fail on new issues

      # --- Your Original Build Step ---
      - name: Build Debug APK
        # Consider changing to ':app:assembleRelease' for pushes to 'main'
        run: ./gradlew :app:assembleDebug

      # --- Your Original Upload Step ---
      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # --- Added: Upload Test Reports (Optional) ---
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest # Adjust path based on your module and build type

      # --- Added: Upload Lint Reports (Optional) ---
      - name: Upload Lint Results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: app/build/reports/lint-results-debug.html # Or lint-results.xml